name: Compile and release
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
       
      - name: Install Typst
        run: |
          wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst-x86_64-unknown-linux-musl.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
          
      - name: Build Typst
        run: |
          mkdir -p build
          typst compile main.typ

      - name: Prepare assets
        run: |
          mkdir -p assets
          cp main.pdf ./assets/

      - name: semver
        uses: anitvam/conventionalcommit-semantic-releasing@v0.7.26
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

