name: Compile and release
on:
  push:
    branches:
      - master

permissions:
  contents: write
  
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Build latex
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Prepare assets
        run: |
          mkdir -p assets
          cp ./build/*.pdf ./assets/

      - name: semver
        uses: anitvam/conventionalcommit-semantic-releasing@v0.7.26
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

